name: terraform-localstack
run-name: Terraform Localstack Testing
on: 
  workflow_dispatch: {}
jobs:
  terraform-localstack-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install terraform
      - name: Install tflocal
        run: pip install terraform-local
      - name: Install LocalStack
        run: |
          pip install localstack
          docker pull localstack/localstack
          localstack start -d
          localstack wait -t 30
      - name: Initialize the Terraform Configuration
        run: tflocal init --var-file local.tfvars
      - name: Validate Terraform Configuration
        run: tflocal validate 
      - name: Run Terraform Plan
        run: tflocal plan --var-file local.tfvars
      - name: Run Terraform Apply
        run: tflocal apply -auto-approve --var-file local.tfvars